Question 1:

In [ ]:
dict1={"Boys":[72,68,70,69,74],"Girls":[63,65,69,62,61]}

list1=[]
x=(len(dict1["Boys"]))
for i in range (x):
  list1.append({"Boys": dict1["Boys"][i],"Girls": dict1["Girls"][i]})
print(list1)

[{'Boys': 72, 'Girls': 63}, {'Boys': 68, 'Girls': 65}, {'Boys': 70, 'Girls': 69}, {'Boys': 69, 'Girls': 62}, {'Boys': 74, 'Girls': 61}]


Question 2:

In [ ]:
import math
import pandas as pd
import numpy as np

arr = [4, 2, 3, 7, 6]
l = np.argsort(arr)
print(l)
# q2
l1 = []
l2 = []
n1 = int(input("Number of elements in arr1 : "))
print("Enter elements for array 1: ")
for x in range(n1):
    l1.append(int(input()))
n1 = int(input("Number of elements in arr2 : "))
print("Enter elements for array 2: ")
for x in range(n1):
    l2.append(int(input()))
Arr = np.array([l1, l2])
print(l1)
print(l2)
print(Arr)

# ---------a----------
print("Mean = ", np.mean(Arr, axis=1))
print("Standard deviation = ", np.std(Arr, axis=1))
print("Variance = ", np.var(Arr, axis=1))

# ----------b----------
B = [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]
l = np.argsort(B)
print(l)

# ----------c----------
print("Shape = ", np.shape(Arr))
print("Type = ", type(Arr))
print("Data type = ", Arr.dtype)
print("Reshape = \n", np.reshape(Arr, (5, 2)))
print("Transpose = \n", np.transpose(Arr))

# ----------d-----------
arr1 = [3, 0, 42, 0, math.nan, math.nan]
a = np.array(arr1)
a1 = np.nonzero(a)
print("Non-zeroes in a = ", a1)
a2 = np.nonzero(a == 0)
print("Zeroes in a = ", a2)
a3 = np.isnan(arr1)
a4 = np.where(a3 == True)
print("NaN values in a = ", a4)

[1 2 0 4 3]


Question 3:

In [ ]:

names = ["axc", "bxbb", "xxb","zzxy","zzc"]
names.sort(key = lambda x:x[-1])
print(names)

['bxbb', 'xxb', 'axc', 'zzc', 'zzxy']


In [ ]:

names1 = ["axc", "bxbb", "xxb","zzxy","zzc"]
names1.sort(key = lambda x:len(x))
print(names1)
dict2={len(name):name for name in names1}
print(dict2)

['axc', 'xxb', 'zzc', 'bxbb', 'zzxy']
{3: 'zzc', 4: 'zzxy'}


Question 4:

In [ ]:
import numpy as np

In [ ]:
arr=np.random.randint(100,size=(4,3))
print(arr)
#axis=1 means along each row
print(arr.mean(axis=1)) 
print(arr.var(axis=1))
print(arr.std(axis=1))


[[88 85 31]
 [16 24 73]
 [87 69 37]
 [28 77 46]]
[68.         37.66666667 64.33333333 50.33333333]
[686.         634.88888889 427.55555556 409.55555556]
[26.19160171 25.19700159 20.67741656 20.23747898]


In [ ]:
arr=np.array([56,48,22,41,78,91,24,46,8,33])
#arr.sort()
print(arr)
print(arr.argsort())
#for i in range(arr.size):
 # print(str(i) + ": " + str(arr[i]))
  

[56 48 22 41 78 91 24 46  8 33]
[8 2 6 9 3 7 1 0 4 5]


In [ ]:
#m=input("enter no. of row")
#n=input("enter no. of col")
m,n=input('enter no. of rows and cols').split()
arr=np.random.randint(10,size=(int(m),int(n)))
print(arr)


enter no. of rows and cols2 3
[[5 7 8]
 [0 1 9]]


In [ ]:
arr= np.array([[1, 0, 3, 4 , np.nan,],[11 , 0 , -1 , np.nan , 0]])
print(np.where(arr==0))
print(np.where(arr!=0))
print(np.where(np.isnan(arr)==True))


In [ ]:
print(arr.shape)
print(arr.dtype)
print(type(arr))

(2, 3)
int64
<class 'numpy.ndarray'>


In [ ]:
print(arr.T)

[[1 9 5]
 [2 9 9]
 [5 2 3]]


In [ ]:
arr1=[]
arr2=[]
arr3=[]
for i in range(int(m)):
  for j in range(int(n)):
    if arr[i][j]==0:
      arr1.append(arr[i][j])
    elif arr[i][j]==np.NaN:
      arr2.append(arr[i][j])
    else:
      arr3.append(arr[i][j])
print(arr1)
print(arr2)
print(arr3)


[]
[]
[1, 2, 5, 9, 9, 2, 5, 9, 3]


Question 5

In [ ]:
import pandas as pd

In [ ]:
arr=np.random.randint(100,size=(50,3))
df=pd.DataFrame(arr,columns=['first','second','third'])

#print(df)
#x=0.1*150
for y in range(15):
  i=np.random.randint(50)
  j=np.random.randint(3)
  if(df.iloc[i,j]!=np.nan):
    df.iat[i,j]=np.nan

print(df)


In [ ]:
df.drop_duplicates(subset='first',keep='first',inplace=True)
print(df)

In [ ]:
df.plot.box()

In [ ]:
sum=df.sum(axis=1)
print("SUM OF DATAFRAME ROW-WISE :\n", sum)
print("\n MAXIMUM SUM OF ROW ELEMENTS IS :",sum.max())
max_sum_index = df.sum(axis=1).idxmax()
print("\nIndex of row having maximum sum is :" ,max_sum_index)
df.drop(index=max_sum_index)

In [ ]:
#for col in df.columns:
  #print(df[col].isnull().sum())
  #df.dropna(axis = 1,thresh=(df[col].isnull().sum()>4),inplace=True)
  #print(df)
for col in df.columns:
 print(col,df[col].isnull().sum())
df.dropna(axis = 1,thresh=(df.shape[0]-5))


In [ ]:
print(df.iloc[1,1])

96


In [ ]:
print(df.isnull().sum().sum())

15


In [ ]:
arr=np.random.rand(50,3)
arr

In [ ]:
df=pd.DataFrame(arr)
df

In [ ]:
row = df.shape[0]  # Gives number of rows
col = df.shape[1]  # Gives number of columns

n=0.1*row*col

while(n!=0):
  i=np.random.randint(row)
  j=np.random.randint(col)
  if(df.iloc[i,j]!=np.nan):
    df.iloc[i,j]=np.nan
  n=n-1
df

In [ ]:
print("Total number of missing values in dataframe: " + str(df.isnull().sum().sum()) )

Total number of missing values in dataframe: 13


In [ ]:
df.dropna(thresh=df.isnull().sum()>5 ,axis=1)

In [ ]:
df.isnull().sum()

0    6
1    4
2    5
dtype: int64

In [ ]:
df.sort_values(0) #sorting values in dataframe on basis of first column

In [ ]:
df.dropna(axis=0, thresh=max(df.sum(axis=1))) 
df.drop_duplicates(subset=0, keep='first')

In [ ]:
df.drop_duplicates(subset=0, keep='first')

In [ ]:
df[0].corr(df[1])

-0.002691888571376212

In [ ]:
df[1].cov(df[2])

-0.0014977844673722195

In [ ]:
#detect and remove outliers

In [ ]:
pd.cut(df[1],5)

Consider two csv files of students of years 2019 and 2020 having following details (student
name, hobby, course)   where coruses are (CShons, BComhons, PSCS) and hobbies are
(writing, painting, music, dancing). Answer the following
i) Find all hobbies types for each course  in both years
ii) Find hobbies which are there in 2019 but not in 2020 for each course
iii) Find common hobbies in both year
iv) Find course name in which students are exploring all hobbies
v) Find count of students exploring each hobby in both year

In [ ]:
import pandas as pd

In [ ]:
df1=pd.read_csv('/content/2019.csv')
df2=pd.read_csv('/content/2020.csv')
#i
print(df2)


#ii
#pd.merge(df1,df2,on='hobby',how='left')
#iii
pd.merge(df1,df2,on='hobby',how='inner')

     name     hobby course
0   Bhavs   drawing   PSCS
1     Ant  football   Bcom
2   Shiks   Singing   PSCS
3  Dhruva   writing   Bcom


name_x    hobby course_x  name_y course_y
0  Palak  drawing       CS   Bhavs     PSCS
1  Mants  writing     Bcom  Dhruva     Bcom